### ISSUE TITLE
Usefulness of set_max_priority() and set_default_priority()

### ISSUE THREAD

**Issue by MechanicalPython** [michaelfletchercgy/dht22_pi#4]
This is less of an issue and more of a query. 

In running this library on a pi zero the following error occurred: 
```
thread 'main' panicked at 'Error setting priority, you may not have cap_sys_nice capability', /home/pi/dht22_pi/src/lib.rs:75:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```
However, when I commented out the set_max_priority() and set_default_priority() functions from the read() function, the code ran properly and gives the correct output. 

Therefore, what is the use of set_max_priority() and set_default_priority()?

**Comment by jonmast** [comment]
@MechanicalPython Setting "max priority" helps ensure the process doesn't get interrupted while performing the read. Reading from the sensor is very sensitive to timing and any interruption can cause the read to fail. It's not strictly required, but removing it would increase the error rate, especially if the system is under some load.

You can use `sudo setcap 'cap_sys_nice=eip' $filename` to set up the necessary permissions for this.

**Comment by MechanicalPython** [comment]
Thank you for clarifying
